### ISSUE TITLE
Current app.js will not run on azure web app

### ISSUE THREAD

**Issue by sanderkooger** [MustansirZia/next-express-bootstrap-boilerplate#2]
If current version is deployed to Azure deployment will result in a 500. 

After troubleshooting I found that changing const express = require('express');
 `app.listen(port);
};

// Start the express server.
start(9001);`

to `app.listen(process.env.PORT);
};

// Start the express server.
start(9001);`

Makes repo run on Azure but then npm run start will not produce a running site locally. 

How do I make this run both local and on Azure?

**Comment by MustansirZia** [comment]
Looks like Azure provides a `PORT` environment variable which you should use to start your express app. 
An easy way for it work would be to write the line `start(9001)` like this.
`start(process.env.PORT || 9001)`
It would make sure that the server starts on the PORT env variable (if provided) and would fall back on `9001` if there is no such variable present (such as inside your local environment).

**Comment by sanderkooger** [comment]
The solution is tested and I can confirm it works! Thanks a bunch. 

Would it be possible to implement this in the upstream you are hosting? 

Also it might be a good idea to add an echo when the server starts ( Server running on %port or env% with all pistons firing)

Thank you!

**Comment by MustansirZia** [comment]
Yes, I'm going to put this in in my next commit. (And the server running log)
You're welcome! 
Please feel free to close the issue now.

**Comment by sanderkooger** [comment]
@MustansirZia I reopened this issue to share a small snippet with you for good azure working 

In package.json please include the package cross-env

```
"scripts": {
    "build": "cd app && next build",
    "postinstall": "cd app && next build",
    "start": "cross-env NODE_ENV=production node app.js",
    "dev": "nodemon --ignore app/ app.js"
  },
```

Also adding the postinstall script is important otherwise Azure web app will not build before a start.
