### ISSUE TITLE
Sass Module Integration

### ISSUE THREAD

**Issue by kilowattkris** [MustansirZia/next-express-bootstrap-boilerplate#3]
Hi! Not an issue, but just wondering if you have any insight on how to get sass modules to work with this boilerplate. Any pointers would be greatly appreciated and thanks for this awesome boilerplate!

**Comment by kilowattkris** [comment]
Nevermind, I missed the part where I have to include it in a style tag in my component. Sorry!

**Comment by MustansirZia** [comment]
@kilowattkris It's wonderful to hear you found it useful! Thank you! 
Well yes, you do need to put the imported style file in the style tag.
