### ISSUE TITLE
Update to new Version?

### ISSUE THREAD

**Issue by Michael-Reich** [MustansirZia/next-express-bootstrap-boilerplate#4]
Are there any plans to update to the latest nextjs Version?

**Comment by MustansirZia** [comment]
Yes, there are. For now, you can clone the repo and update the version manually.

**Comment by MustansirZia** [comment]
@Michael-Reich Done. The dependencies have been updated including next.js. (`^7.0.2`).
Please update to the latest npm version `0.1.0`.
