### ISSUE TITLE
Can't access rendering data into React component

### ISSUE THREAD

**Issue by lePioo** [MustansirZia/next-express-bootstrap-boilerplate#6]
Hi, in your example you send an object through render method:
`app.get('/main', (req, res) => req.app.render(req, res, '/', {
        routeParam: req.params.routeParam
    }));`
But how to access it after that?
I tried to retrieve it into getInitialProps method parameter but it's not there..
`class Index extends React.Component {
  static async getInitialProps({ req }) {
    console.log(req.routeParam);`

**Comment by MustansirZia** [comment]
In the component try the following.
```js
class Index extends React.Component { static async getInitialProps({ url }) { console.log(url.query.routeParam);
```

**Comment by lePioo** [comment]
{query} is not undefined but it's an empty object..
`class Index extends React.Component {
 static async getInitialProps({ query }) { 
console.log(query); //{}`

**Comment by MustansirZia** [comment]
In your Express.js handlers, you're sending the `routeParam` on `/main` endpoint. Are you hitting the same `/main` endpoint on your browser? I ran the example and I was able to get the param in `{ query }` as `query.routeParam`.

**Comment by lePioo** [comment]
You're right ! Thanks a lot !
