### ISSUE TITLE
sudo npm i -g next-express-bootstrap-boilerplate  does not work

### ISSUE THREAD

**Issue by H3RSKO** [MustansirZia/next-express-bootstrap-boilerplate#7]
I get this error why trying to run: sudo npm i -g next-express-bootstrap-boilerplate

```
Unhandled rejection Error: EISDIR: illegal operation on a directory, open '/Users/user/.npm/_cacache/content-v2/sha512/34/cd'

npm ERR! cb() never called!
```

log: 
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'i',
1 verbose cli   '-g',
1 verbose cli   'next-express-bootstrap-boilerplate' ]
2 info using npm@6.7.0
3 info using node@v8.12.0
4 verbose npm-session c117a29c64dd2f85
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 timing npm Completed in 1240ms
8 error cb() never called!

**Comment by MustansirZia** [comment]
I'm not so sure if this has something to do with the package itself. 
Try the following commands first to clean your npm cache.
For `npm >= 5`
`sudo npm cache verify`
For others.
`sudo npm cache clean`

**Comment by H3RSKO** [comment]
Didn't help:

`sudo npm cache verify` gives me:
```
Cache verified and compressed (~/.npm/_cacache):
Content verified: 3978 (122672040 bytes)
Content garbage-collected: 1422 (66270254 bytes)
Index entries: 6242
Finished in 10.065s
```
But then when I ran `sudo npm i -g next-express-bootstrap-boilerplate` again I got the same error as before.

**Comment by MustansirZia** [comment]
Try clearing the entire cache now, please.
`sudo npm cache clear`.

**Comment by H3RSKO** [comment]
I think I'm running into this problem which seems pretty common: https://npm.community/t/crash-npm-err-cb-never-called/858/10

**Comment by MustansirZia** [comment]
@H3RSKO close the issue if you're satisfied.

**Comment by MustansirZia** [comment]
Closing due inactivity.
